apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      labels:
        app: app-authors
    spec:
      containers:
        - name: app-authors
          image: santiagochango/app_authors_helidon
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: JAVAX_SQL_DATASOURCE_MAIN_USERNAME
              value: examen_santi
            - name: JAVAX_SQL_DATASOURCE_MAIN_PASSWORD
              value: LwyTtSghB1UW3QIfi2EfiQJ7b0fZMjfs
            - name: JAVAX_SQL_DATASOURCE_MAIN_URL
              value: jdbc:postgresql://dpg-cqlcvgjv2p9s73alvk8g-a.oregon-postgres.render.com/examendistribuida
            - name: SERVER_PORT
              value: "8080"
            - name: CORS_ALLOW_ORIGIN
              value: "*"
            - name: CORS_ALLOW_HEADERS
              value: "origin, content-type, accept, authorization"
            - name: CORS_ALLOW_METHODS
              value: "GET, POST, PUT, DELETE, OPTIONS, HEAD"
            - name: CORS_ALLOW_CREDENTIALS
              value: "true"
            - name: CORS_EXPOSE_HEADERS
              value: "*"
            - name: CORS_MAX_AGE
              value: "3600"
---
apiVersion: v1
kind: Service
metadata:
  name: app-author-service
spec:
  type: LoadBalancer
  selector:
    app: app-authors
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-books
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-books
  template:
    metadata:
      labels:
        app: app-books
    spec:
      containers:
        - name: app-books
          image: santiagochango/app_books_helidon
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: JAVAX_SQL_DATASOURCE_MAIN_USERNAME
              value: examen_santi
            - name: JAVAX_SQL_DATASOURCE_MAIN_PASSWORD
              value: LwyTtSghB1UW3QIfi2EfiQJ7b0fZMjfs
            - name: JAVAX_SQL_DATASOURCE_MAIN_URL
              value: jdbc:postgresql://dpg-cqlcvgjv2p9s73alvk8g-a.oregon-postgres.render.com/examendistribuida
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_CORS_ORIGINS
              value: "*"
            - name: SERVER_CORS_METHODS
              value: "GET,POST,PUT,DELETE,OPTIONS"
            - name: SERVER_CORS_HEADERS
              value: "accept,authorization,content-type,x-requested-with"
            - name: SERVER_CORS_EXPOSED_HEADERS
              value: "location,link"
            - name: APP_AUTHORS_URL
              value: http://app-author-service:8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-books-service
spec:
  type: LoadBalancer
  selector:
    app: app-books
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080