create sequence authors_SEQ start with 1 increment by 50;
create table authors (id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table books (author_id integer, id serial not null, price numeric(38,2), isbn varchar(255), title varchar(255), primary key (id));
create table books (author_id integer, id serial not null, price numeric(38,2), isbn varchar(255), title varchar(255), primary key (id));
create table books (author_id integer, id serial not null, price numeric(38,2), isbn varchar(255), title varchar(255), primary key (id));
create table books (author_id integer, id serial not null, price numeric(38,2), isbn varchar(255), title varchar(255), primary key (id));
create sequence authors_SEQ start with 1 increment by 50;
create table authors (id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table books (author_id integer, id serial not null, price numeric(38,2), isbn varchar(255), title varchar(255), primary key (id));
create sequence authors_SEQ start with 1 increment by 50;
create table authors (id integer not null, apellido varchar(255), nombre varchar(255), primary key (id));
create table books (author_id integer, id serial not null, price numeric(38,2), isbn varchar(255), title varchar(255), primary key (id));
